version: "3.8"
services:
    bot:
        build:
            context: ../..
            dockerfile: .docker/${TAG_NAME}/Dockerfile
        image: ${TAG_NAME}:${TAG_VERSION}
        container_name: ${TAG_NAME}
        restart: always
        volumes:
            - type: volume
              source: db_data
              target: ${DATABASE_CONTAINER_PATH}

volumes:
    db_data:
        driver: local
        driver_opts:
            type: none
            device: ${DATABASE_HOST_PATH}
            o: bind
