version: "3.8"
services:
    bot:
        build:
            context: ..
            dockerfile: .docker/${TAG_NAME}/Dockerfile
        image: ${TAG_NAME}:${TAG_VERSION}
        container_name: ${TAG_NAME}
        restart: always
        volumes:
            - type: volume
              source: db_data
              target: /db

volumes:
    db_data:
        driver: local
        driver_opts:
            type: none
            # CHANGE THE FOLLOWING LINE IF NEEDED
            device: D:\Documents\DiscordBot\db
            o: bind
